import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {apiRequest,csv,formatDate,signIn} from "./api.js";
import "./styles.css";

const tabs=["overview","plan","operations","watchlists","radars","runs","signals","alerts","digests"];

function App(){
 const[token,setToken]=useState("");const[email,setEmail]=useState("");const[workspaceId,setWorkspaceId]=useState("");const[session,setSession]=useState(null);const[tab,setTab]=useState("overview");const[data,setData]=useState({});const[state,setState]=useState("signed-out");const[message,setMessage]=useState("");
 async function login(loginEmail,password){setState("loading");setMessage("");try{const auth=await signIn(loginEmail,password);setToken(auth.accessToken);setEmail(auth.email);const next=await apiRequest("/api/v1/session",auth.accessToken);setSession(next);const first=next.workspaces?.[0]?.workspace_id||"";setWorkspaceId(first);setState(first?"ready":"empty");}catch{setState("error");setMessage("Sign-in failed.");setToken("");}}
 function logout(){setToken("");setEmail("");setWorkspaceId("");setSession(null);setData({});setState("signed-out");}
 if(!token)return <Login onLogin={login} state={state} message={message}/>;
 return <div className="shell"><header><div><h1>TrendCite Pro</h1><p>Evidence-first trend intelligence</p></div><div className="identity"><span>{email}</span><button className="ghost" onClick={logout}>Sign out</button></div></header>
 <section className="workspace-bar"><label>Workspace<select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}>{(session?.workspaces||[]).map(w=><option key={w.workspace_id} value={w.workspace_id}>{w.name}</option>)}</select></label><span className={session?.mutations_enabled?"badge active":"badge"}>{session?.mutations_enabled?"Nonprod editing enabled":"Read only"}</span></section>
 {!workspaceId?<StatePanel title="No workspace access" detail="Your account has no TrendCite workspace membership."/>:<><nav>{tabs.map(name=><button key={name} className={tab===name?"selected":""} onClick={()=>setTab(name)}>{name}</button>)}</nav><WorkspaceView token={token} workspaceId={workspaceId} tab={tab} mutationsEnabled={Boolean(session?.mutations_enabled)} data={data} setData={setData}/></>}</div>;
}
function Login({onLogin,state,message}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");async function submit(e){e.preventDefault();const secret=password;setPassword("");await onLogin(email.trim(),secret);}return <main className="login"><form className="card" onSubmit={submit}><h1>TrendCite Pro</h1><p>Sign in to your non-production customer workspace.</p><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={state==="loading"}>{state==="loading"?"Signing in…":"Sign in"}</button>{message&&<p className="error">{message}</p>}<small>Credentials and access tokens are not stored in browser storage.</small></form></main>;}
function WorkspaceView({token,workspaceId,tab,mutationsEnabled,data,setData}){const[status,setStatus]=useState("loading");const[error,setError]=useState("");const endpoint=useMemo(()=>{const root=`/api/v1/workspaces/${encodeURIComponent(workspaceId)}`;return{overview:root,plan:`${root}/entitlements`,operations:`${root}/operations`,watchlists:`${root}/watchlists`,radars:`${root}/radars`,runs:`${root}/runs`,signals:`${root}/signals`,alerts:`${root}/alerts`,digests:`${root}/digests`}[tab]},[workspaceId,tab]);async function load(){setStatus("loading");setError("");try{const payload=await apiRequest(endpoint,token);setData(old=>({...old,[tab]:payload}));const arrays=Object.values(payload).filter(Array.isArray);setStatus(arrays.length&&arrays.every(v=>v.length===0)?"empty":"ready");}catch(err){setStatus(err.status===404?"denied":"unavailable");setError(err.code||"unavailable");}}useEffect(()=>{load();},[endpoint]);if(status==="loading")return <StatePanel title="Loading…" detail="Fetching current workspace data."/>;if(status==="denied")return <StatePanel title="Access denied" detail="This workspace or object is not available to your account."/>;if(status==="unavailable")return <StatePanel title="Temporarily unavailable" detail={error}/>;const payload=data[tab]||{};if(tab==="overview")return <Overview payload={payload}/>;if(tab==="plan")return <PlanUsage payload={payload}/>;if(tab==="operations")return <Operations payload={payload}/>;if(tab==="watchlists")return <Watchlists payload={payload} token={token} workspaceId={workspaceId} editable={mutationsEnabled} reload={load}/>;if(tab==="radars")return <Radars payload={payload} token={token} workspaceId={workspaceId} editable={mutationsEnabled} reload={load}/>;if(tab==="runs")return <Collection title="Runs" items={payload.runs} render={x=><><b>{x.radar_name}</b><span>{x.status}</span><small>{formatDate(x.started_at)}</small></>}/>;if(tab==="signals")return <Collection title="Signals" items={payload.signals} render={x=><><b>{x.label}</b><span>Strength {x.strength}</span><small>{formatDate(x.last_matched_at)}</small></>}/>;if(tab==="alerts")return <Collection title="Alerts" items={payload.alerts} render={x=><><b>{x.subject}</b><span>{x.delivery_state}</span><small>{formatDate(x.created_at)}</small></>}/>;return <Collection title="Digests" items={payload.digests} render={x=><><b>{x.subject}</b><span>{x.item_count} items · {x.delivery_state}</span><small>{formatDate(x.created_at)}</small></>}/>;}
function Overview({payload}){const w=payload.workspace;return <section className="panel"><h2>{w?.name||"Workspace"}</h2><p>Role: <b>{w?.role||"—"}</b></p><p>Created: {formatDate(w?.created_at)}</p></section>;}
function PlanUsage({payload}){const e=payload.entitlements||{};const usage=e.usage||{};const quotas=e.quotas||{};return <section className="panel"><h2>Plan & Usage</h2><p>Effective plan: <b>{e.display_name||e.plan_key||"No entitlement assigned"}</b></p>{Object.keys(usage).length===0?<p>No metered usage in the current period.</p>:<div className="collection">{Object.entries(usage).map(([kind,used])=>{const q=Object.values(quotas).find(x=>x?.kind===kind);return <article key={kind}><b>{kind}</b><span>{used}{q?.limit!=null?` / ${q.limit}`:""}</span><small>{q?.limit!=null?"monthly quota":"metered"}</small></article>})}</div>}</section>;}
function Operations({payload}){const o=payload.operations||{};const rows=[["Scheduler",o.scheduler_stale?"stale":"healthy",o.scheduler_last_seen_at?formatDate(o.scheduler_last_seen_at):"No heartbeat"],["Enabled schedules",o.enabled_schedules??0,`${o.overdue_schedules??0} overdue`],["Stale pending ticks",o.pending_stale_ticks??0,"eligible for recovery"],["Expired running ticks",o.expired_running_ticks??0,"lease expired"],["Retryable failed ticks",o.retryable_failed_ticks??0,"attempt budget remains"],["Exhausted failed ticks",o.exhausted_failed_ticks??0,"terminal"],["Recovery actions (24h)",o.recovery_actions_24h??0,"durable audit"],["Queue failures (24h)",o.queue_failures_24h??0,`${o.queue_failures_at_retry_limit_24h??0} at retry limit`]];return <section className="panel"><h2>Operations</h2><div className="collection">{rows.map(([name,value,detail])=><article key={name}><b>{name}</b><span>{String(value)}</span><small>{detail}</small></article>)}</div></section>;}
function Watchlists({payload,token,workspaceId,editable,reload}){return <section className="panel"><h2>Watchlists</h2>{editable&&<WatchlistForm token={token} workspaceId={workspaceId} reload={reload}/>}<Collection items={payload.watchlists} render={x=><><b>{x.name}</b><span>{(x.latest_version?.include_terms||[]).join(", ")||"No terms"}</span><small>v{x.latest_version?.version_number||"—"}</small></>}/></section>;}
function WatchlistForm({token,workspaceId,reload}){const[name,setName]=useState("");const[terms,setTerms]=useState("");const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{await apiRequest(`/api/v1/workspaces/${encodeURIComponent(workspaceId)}/watchlists`,token,{method:"POST",body:JSON.stringify({name,include_terms:csv(terms),exclude_terms:[],entities:[],domains:[],match_mode:"any"})});setName("");setTerms("");await reload();}finally{setBusy(false);}}return <form className="inline-form" onSubmit={submit}><input required placeholder="Watchlist name" value={name} onChange={e=>setName(e.target.value)}/><input required placeholder="terms, comma, separated" value={terms} onChange={e=>setTerms(e.target.value)}/><button disabled={busy}>{busy?"Saving…":"Create"}</button></form>;}
function Radars({payload,token,workspaceId,editable,reload}){const[watchlists,setWatchlists]=useState([]);useEffect(()=>{apiRequest(`/api/v1/workspaces/${encodeURIComponent(workspaceId)}/watchlists`,token).then(p=>setWatchlists(p.watchlists||[])).catch(()=>setWatchlists([]));},[token,workspaceId]);return <section className="panel"><h2>Radars</h2>{editable&&<RadarForm token={token} workspaceId={workspaceId} watchlists={watchlists} reload={reload}/>}<Collection items={payload.radars} render={x=><><b>{x.name}</b><span>{(x.latest_version?.sources||[]).join(", ")}</span><small>v{x.latest_version?.version_number||"—"}</small></>}/></section>;}
function RadarForm({token,workspaceId,watchlists,reload}){const[name,setName]=useState("");const[watchlistId,setWatchlistId]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{if(!watchlistId&&watchlists[0])setWatchlistId(watchlists[0].watchlist_id);},[watchlists,watchlistId]);async function submit(e){e.preventDefault();setBusy(true);try{await apiRequest(`/api/v1/workspaces/${encodeURIComponent(workspaceId)}/radars`,token,{method:"POST",body:JSON.stringify({name,watchlist_ids:[watchlistId],sources:["hackernews","github"],niche:[],top:5})});setName("");await reload();}finally{setBusy(false);}}return <form className="inline-form" onSubmit={submit}><input required placeholder="Radar name" value={name} onChange={e=>setName(e.target.value)}/><select value={watchlistId} onChange={e=>setWatchlistId(e.target.value)}>{watchlists.map(w=><option key={w.watchlist_id} value={w.watchlist_id}>{w.name}</option>)}</select><button disabled={busy||!watchlistId}>{busy?"Saving…":"Create"}</button></form>;}
function Collection({title,items=[],render}){return <section className="collection">{title&&<h2>{title}</h2>}{!items?.length?<StatePanel title="No data yet" detail="There is nothing to show for this workspace."/>:items.map((item,index)=><article key={item.watchlist_id||item.radar_id||item.run_id||item.signal_id||item.alert_id||item.digest_id||index}>{render(item)}</article>)}</section>;}
function StatePanel({title,detail}){return <section className="state"><h2>{title}</h2><p>{detail}</p></section>;}
createRoot(document.getElementById("root")).render(<App/>);
